{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golden-axe-backend
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: golden-axe
    app.kubernetes.io/component: backend
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hosts.backend }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: golden-axe-backend
                port:
                  number: {{ .Values.backend.service.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golden-axe-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: golden-axe
    app.kubernetes.io/component: frontend
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hosts.frontend }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: golden-axe-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}
