{{- range .Values.onePasswordItems }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  itemPath: {{ .path | quote }}
{{- end }}
