name: Main
on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  NODE_ENV: production
  WRANGLER_SEND_METRICS: false

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  deploy-explorer:
    name: Deploy Explorer
    needs: verify
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      app: explorer
      environments: '["testnet","moderato","devnet","presto"]'

  deploy-fee-payer:
    name: Deploy Fee Payer
    needs: verify
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      app: fee-payer
      environments: '["privy","devnet","testnet","moderato","mainnet"]'

  deploy-contract-verification:
    name: Deploy Contract Verification
    needs: verify
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      app: contract-verification
      environments: '[""]'

  deploy-key-manager:
    name: Deploy Key Manager
    needs: verify
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      app: key-manager
      environments: '[""]'

  deploy-og:
    name: Deploy OG
    needs: verify
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      app: og
      environments: '[""]'

  deploy-tokenlist:
    name: Deploy Tokenlist
    needs: verify
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      app: tokenlist
      environments: '[""]'
